### PR TITLE
Oscar

### PR DESCRIPTION
**Pull request by oscarnt4**
Player prefab created with c# script for movement and jumping etc.

### CODE REVIEW

**Comment by analopesmartinez** [comment]
Hi!

**Comment by oscarnt4** [comment]
> Hi!

HEY

**Comment by oscarnt4** [comment]
unlucky, try again!

**Comment by analopesmartinez** [comment]
Lol idk what to do now

**Review by analopesmartinez — APPROVED** [review]
I think I can approve it! Yay!

**Pull request merged**
